openapi: 3.0.1
info:
  contact:
    email: apisupport@mastercard.com
    name: API Support
    url: https://developer.mastercard.com/support
  description: Merchants Locations API
  title: Merchants Locations API
  version: 2.0.0
servers:
- description: Production server
  url: https://api.mastercard.com/locations/merchants
- description: Sandbox server
  url: https://sandbox.api.mastercard.com/locations/merchants
tags:
- description: Returns a list of merchant categories
  name: Categories
- description: Retrieve a list of countries and country subdivisions
  name: Countries
- description: Retrieve merchant detail for a given geo location
  name: Merchants
paths:
  /countries:
    get:
      description: Returns a list of countries
      operationId: getCountries
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Countries'
          description: List of Countries
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading merchant information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of countries
      tags:
      - Countries
      x-accepts: application/json
  /country-subdivisions:
    get:
      description: Returns a list of country subdivisions for a given country
      operationId: getCountrySubdivisions
      parameters:
      - description: Country Code
        example: USA
        explode: true
        in: query
        name: country_code
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountrySubdivisions'
          description: List of Country Subdivisions
        "400":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: latitude
                    ReasonCode: INVALID_INPUT_VALUE
                    Description: Latitude is missing, invalid, or could not be determined
                      from address fields.
                    Recoverable: false
                    Details: null
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Something was wrong with the request.
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading merchant information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of country subdivisions
      tags:
      - Countries
      x-accepts: application/json
  /categories:
    get:
      description: Returns a list of merchant categories
      operationId: getMerchantCategories
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
          description: List of Merchant Categories
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading merchant information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of merchant categories
      tags:
      - Categories
      x-accepts: application/json
  /searches:
    post:
      description: Returns detailed information on merchants based on the provided
        query parameters
      operationId: getMerchants
      parameters:
      - description: The number of items to be retrieved
        example: 25
        explode: true
        in: query
        name: limit
        required: false
        schema:
          type: integer
        style: form
      - description: The page offset used for the query
        example: 1
        explode: true
        in: query
        name: offset
        required: false
        schema:
          type: integer
        style: form
      - description: Distance measurement for calculating the radius search. Optional
          The length of distance from the centroid point. Value string(<25). The default
          will be 5 units
        example: 5
        explode: true
        in: query
        name: distance
        required: false
        schema:
          type: integer
        style: form
      - description: Unit of measurement for calculating the radius search. Optional.
          Measurement of distance unit in miles or kilometers. Value string (MILE
          or KM)
        example: MILE
        explode: true
        in: query
        name: distance_unit
        required: false
        schema:
          enum:
          - MILE
          - KM
          type: string
        style: form
      requestBody:
        $ref: '#/components/requestBodies/MerchantSearch'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchants'
          description: List of Merchant details
        "400":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: latitude
                    ReasonCode: INVALID_INPUT_VALUE
                    Description: Latitude is missing, invalid, or could not be determined
                      from address fields.
                    Recoverable: false
                    Details: null
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Something was wrong with the request.
        "401":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: UNAUTHORIZED
                    Description: We couldn't recognize you
                    Recoverable: false
                    Details: Full authentication is required to access this resource
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Authentication information was missing or invalid.
        "403":
          content:
            application/json:
              example:
                Errors:
                - Error:
                    Source: locations-merchants-api
                    ReasonCode: PERMISSION_DENIED
                    Description: You don't seem authorized to do that
                    Recoverable: false
                    Details: Reading merchant information requires readonly permissions
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Insufficient permissions for interacting with the resource.
      summary: Get a list of merchant details
      tags:
      - Merchants
      x-contentType: application/json
      x-accepts: application/json
components:
  parameters:
    CountryParam:
      description: Country Code
      example: USA
      explode: true
      in: query
      name: country_code
      required: true
      schema:
        type: string
      style: form
    LimitParam:
      description: The number of items to be retrieved
      example: 25
      explode: true
      in: query
      name: limit
      required: false
      schema:
        type: integer
      style: form
    OffsetParam:
      description: The page offset used for the query
      example: 1
      explode: true
      in: query
      name: offset
      required: false
      schema:
        type: integer
      style: form
    DistanceParam:
      description: Distance measurement for calculating the radius search. Optional
        The length of distance from the centroid point. Value string(<25). The default
        will be 5 units
      example: 5
      explode: true
      in: query
      name: distance
      required: false
      schema:
        type: integer
      style: form
    DistanceUnitParam:
      description: Unit of measurement for calculating the radius search. Optional.
        Measurement of distance unit in miles or kilometers. Value string (MILE or
        KM)
      example: MILE
      explode: true
      in: query
      name: distance_unit
      required: false
      schema:
        enum:
        - MILE
        - KM
        type: string
      style: form
  requestBodies:
    MerchantSearch:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantSearch'
      description: A JSON object containing item data
      required: true
  responses:
    Countries:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Countries'
      description: List of Countries
    CountrySubdivisions:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CountrySubdivisions'
      description: List of Country Subdivisions
    Categories:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Categories'
      description: List of Merchant Categories
    Merchants:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Merchants'
      description: List of Merchant details
    BadRequestError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: latitude
                ReasonCode: INVALID_INPUT_VALUE
                Description: Latitude is missing, invalid, or could not be determined
                  from address fields.
                Recoverable: false
                Details: null
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Something was wrong with the request.
    UnauthorizedError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: locations-merchants-api
                ReasonCode: UNAUTHORIZED
                Description: We couldn't recognize you
                Recoverable: false
                Details: Full authentication is required to access this resource
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Authentication information was missing or invalid.
    ForbiddenError:
      content:
        application/json:
          example:
            Errors:
            - Error:
                Source: locations-merchants-api
                ReasonCode: PERMISSION_DENIED
                Description: You don't seem authorized to do that
                Recoverable: false
                Details: Reading merchant information requires readonly permissions
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      description: Insufficient permissions for interacting with the resource.
  schemas:
    Country:
      description: Available information for the Country such as the name and code
      example:
        Country:
          countryCode: AUS
          countryName: Australia
      properties:
        countryCode:
          description: Three digit alpha country code as defined in ISO 3166-1
          example: AUS
          maxLength: 3
          minLength: 3
          type: string
        countryName:
          description: Name of the country
          example: Australia
          type: string
      type: object
    CountrySubdivision:
      description: Available information the Country Subdivision such as the name
        and code
      example:
        CountrySubdivision:
          countrySubdivisionCode: AL
          countrySubdivisionName: Alabama
      properties:
        countrySubdivisionCode:
          description: Abbreviated code for the state or province
          example: AL
          maxLength: 2
          minLength: 2
          type: string
        countrySubdivisionName:
          description: Name of the country subdivision
          example: Alabama
          type: string
      type: object
    Category:
      description: Merchant Category Name and id
      example:
        Category:
          categoryName: Apparel
          categoryId: "1"
      properties:
        categoryId:
          description: Category Id
          example: "1"
          maxLength: 2
          minLength: 1
          type: string
        categoryName:
          description: Name of the category
          example: Apparel
          type: string
      type: object
    MerchantSearch:
      description: Merchant Search Request Info
      example:
        offerMerchantId: "1143109"
        city: SAINT PETERS
        countryCode: USA
        latitude: "38.795089"
        postalCode: "63376"
        countrySubdivisionCode: MO
        addressLine1: 4033 Veterans Memorial Pkwy
        addressLine2: Apt 1
        merchantCategory: "0"
        merchantType: easysavings
        longitude: -90.572346
      properties:
        addressLine1:
          description: Line 1 of the street address for the merchant location. Usually
            includes the street number and name. This parameter is ignored if latitude
            and longitude are provided. If you provide this parameter you must also
            provide the Country parameter and either City parameter or PostalCode
            parameter.
          example: 4033 Veterans Memorial Pkwy
          type: string
        addressLine2:
          description: Line 2 of the street address usually an apartment number or
            suite number. This parameter is used rarely and is ignored if latitude
            and longitude are provided. If you provide this parameter you must also
            provide the Country parameter and either City parameter or PostalCode
            parameter.
          example: Apt 1
          type: string
        city:
          description: The name of the city for a merchant location. This parameter
            is ignored if latitude and longitude are provided. If you provide this
            parameter you must also provide the Country parameter.
          example: SAINT PETERS
          type: string
        countryCode:
          description: Any two digit country code for an Merchant location. Valid
            values are two digit alpha country code. This parameter is ignored if
            latitude and longitude are provided. This parameter is required if any
            other address information is provided including AddressLine1 AddressLine2
            City PostalCode or CountrySubdivision.
          example: USA
          type: string
        countrySubdivisionCode:
          description: The state or province for a merchant location (only supported
            for US and Canada locations). This parameter is ignored if latitude and
            longitude are provided. If you provide this parameter you must also provide
            the Country parameter.
          example: MO
          type: string
        latitude:
          description: The latitude of a merchant location. If latitude is provided
            longitude must also be provided.
          example: "38.795089"
          type: string
        longitude:
          description: The longitude of a merchant location. If longitude is provided
            latitude must also be provided.
          example: -90.572346
          type: string
        merchantCategory:
          description: Category Id of the merchant location. See the Categories resource
            for a list of valid categories.  Input may be a comma delimited list of
            category ids.
          example: "0"
          type: string
        merchantType:
          description: Type of merchant location. Options are 'paypass' 'repower'
            'easysavings' and 'cashback'.
          example: easysavings
          type: string
        offerMerchantId:
          description: Unique identifier that represents the merchant sponsor of an
            offer. Any valid merchant ID.
          example: "1143109"
          type: string
        postalCode:
          description: The zip code or postal code for an Merchant location. This
            parameter is ignored if latitude and longitude are provided. If you provide
            this parameter you must also provide the Country parameter.
          example: "63376"
          type: string
      title: MerchantSearch
      type: object
    Merchant:
      description: Merchant detail information
      example:
        cashbackMaximumAmount: "40"
        distanceUnit: MILE
        countrySubdivisionName: Missouri
        distance: 1.75723000000001
        city: OFallon
        latitude: "38.670337"
        postalCode: "63366"
        isPayPassRegister: true
        isRepowerByCardSwipeSupported: true
        isRepowerByMoneyPakSupported: true
        websiteUrl: www.mcdondalds.com
        countryCode: US
        countrySubdivisionCode: MO
        addressLine1: 1 Oak Street
        addressLine2: Apt 1
        id: 1505451132
        isPayPassVendingMachine: true
        longitude: -90.443727
        locationName: QUIK TRIP STORE 1
        isPayPassTicketing: true
        isPayPassPharmacy: true
        isPayPassTollBooth: true
        easySavingsMerchantOfferId: "1143109"
        isPayPassFuelPump: true
        phoneNumber: "8165442210"
        geocodingResult: S8HPNTSCZA
        isPayPassDriveThrough: true
        isPayPassConcession: true
        countryName: United States
        category: 10 - Grocery Stores & Supermarkets
      properties:
        addressLine1:
          description: Line 1 of the street address for the merchant location. Usually
            includes the street number and name.
          example: 1 Oak Street
          type: string
        addressLine2:
          description: Line 2 of the street address usually an apartment number or
            suite number.
          example: Apt 1
          type: string
        cashbackMaximumAmount:
          description: Maximum cashback amount permitted at the location.
          example: "40"
          type: string
        category:
          description: Merchant's category
          example: 10 - Grocery Stores & Supermarkets
          type: string
        countryCode:
          description: Two digit alpha country code as defined in ISO
          example: US
          type: string
        countryName:
          description: Name of the country.
          example: United States
          type: string
        countrySubdivisionCode:
          description: Code of the state or province for a merchant location.
          example: MO
          type: string
        countrySubdivisionName:
          description: Name of the state or province for a merchant location.
          example: Missouri
          type: string
        city:
          description: The name of the city for a merchant location.
          example: OFallon
          type: string
        distance:
          description: This is the numerical value for the distance from the provided
            location to the selected merchant.
          example: 1.75723000000001
          format: double
          type: number
        distanceUnit:
          description: This is the unit of measure value for the distance from the
            provided location to the selected merchant. Options are KM and MILE.
          example: MILE
          type: string
        easySavingsMerchantOfferId:
          description: Merchant's Easy Savings Offer Id
          example: "1143109"
          type: string
        geocodingResult:
          description: GeocodingResult for the merchant
          example: S8HPNTSCZA
          type: string
        id:
          description: Numerical merchant identifier.
          example: 1505451132
          format: int32
          type: integer
        isPayPassConcession:
          description: Boolean value which indicates if the concession area is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isPayPassPharmacy:
          description: Boolean value which indicates if the pharmacy is equipped with
            a PayPass card reader.
          example: true
          type: boolean
        isPayPassFuelPump:
          description: Boolean value which indicates if the fuel pump is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isPayPassTollBooth:
          description: Boolean value which indicates if the toll booth is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isPayPassDriveThrough:
          description: Boolean value which indicates if the drive thru is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isPayPassRegister:
          description: Boolean value which indicates if the register is equipped with
            a PayPass card reader.
          example: true
          type: boolean
        isPayPassTicketing:
          description: Boolean value which indicates if the ticketing area is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isPayPassVendingMachine:
          description: Boolean value which indicates if the vending machine is equipped
            with a PayPass card reader.
          example: true
          type: boolean
        isRepowerByCardSwipeSupported:
          description: Boolean value which indicates if the repower card load type
            at this merchant supports Card Swipe.
          example: true
          type: boolean
        isRepowerByMoneyPakSupported:
          description: Boolean value which indicates if the repower card load type
            at this merchant supports MoneyPak.
          example: true
          type: boolean
        latitude:
          description: The latitude of the merchant
          example: "38.670337"
          type: string
        locationName:
          description: Merchant's Name
          example: QUIK TRIP STORE 1
          type: string
        longitude:
          description: The longitude of the merchant.
          example: -90.443727
          type: string
        phoneNumber:
          description: Merchant's phone number
          example: "8165442210"
          type: string
        postalCode:
          description: The postal code of the Merchant location.
          example: "63366"
          type: string
        websiteUrl:
          description: Merchant's website URL address
          example: www.mcdondalds.com
          type: string
      title: Merchant
      type: object
    Merchants:
      example:
        total: 210
        offset: 1
        count: 10
        limit: 10
        merchants:
        - cashbackMaximumAmount: "40"
          distanceUnit: MILE
          countrySubdivisionName: Missouri
          distance: 1.75723000000001
          city: OFallon
          latitude: "38.670337"
          postalCode: "63366"
          isPayPassRegister: true
          isRepowerByCardSwipeSupported: true
          isRepowerByMoneyPakSupported: true
          websiteUrl: www.mcdondalds.com
          countryCode: US
          countrySubdivisionCode: MO
          addressLine1: 1 Oak Street
          addressLine2: Apt 1
          id: 1505451132
          isPayPassVendingMachine: true
          longitude: -90.443727
          locationName: QUIK TRIP STORE 1
          isPayPassTicketing: true
          isPayPassPharmacy: true
          isPayPassTollBooth: true
          easySavingsMerchantOfferId: "1143109"
          isPayPassFuelPump: true
          phoneNumber: "8165442210"
          geocodingResult: S8HPNTSCZA
          isPayPassDriveThrough: true
          isPayPassConcession: true
          countryName: United States
          category: 10 - Grocery Stores & Supermarkets
        - cashbackMaximumAmount: "40"
          distanceUnit: MILE
          countrySubdivisionName: Missouri
          distance: 1.75723000000001
          city: OFallon
          latitude: "38.670337"
          postalCode: "63366"
          isPayPassRegister: true
          isRepowerByCardSwipeSupported: true
          isRepowerByMoneyPakSupported: true
          websiteUrl: www.mcdondalds.com
          countryCode: US
          countrySubdivisionCode: MO
          addressLine1: 1 Oak Street
          addressLine2: Apt 1
          id: 1505451132
          isPayPassVendingMachine: true
          longitude: -90.443727
          locationName: QUIK TRIP STORE 1
          isPayPassTicketing: true
          isPayPassPharmacy: true
          isPayPassTollBooth: true
          easySavingsMerchantOfferId: "1143109"
          isPayPassFuelPump: true
          phoneNumber: "8165442210"
          geocodingResult: S8HPNTSCZA
          isPayPassDriveThrough: true
          isPayPassConcession: true
          countryName: United States
          category: 10 - Grocery Stores & Supermarkets
      properties:
        count:
          description: The number of items in the retrieved data set
          example: 10
          format: int32
          type: integer
        limit:
          description: The number of items requested to be retrieved
          example: 10
          format: int32
          type: integer
        offset:
          description: The page offset used for the query
          example: 1
          format: int32
          type: integer
        total:
          description: The total number of merchants available to be retrieved
          example: 210
          format: int32
          type: integer
        merchants:
          description: The list of merchants retrieved
          items:
            $ref: '#/components/schemas/Merchant'
          type: array
      title: Merchants
      type: object
    Error:
      description: Details of the error condition such as the source of the error,
        reason code for the error, if the error is recoverable, and details about
        the error
      properties:
        Source:
          description: The application that generated this error
          example: latitude
          maxLength: 150
          minLength: 0
          type: string
        ReasonCode:
          description: A unique constant identifying the error case encountered during
            transaction processing
          example: INVALID_INPUT_VALUE
          maxLength: 150
          minLength: 0
          type: string
        Description:
          description: Short description of the ReasonCode field
          example: Latitude is missing, invalid, or could not be determined from address
            fields.
          maxLength: 150
          minLength: 0
          type: string
        Recoverable:
          description: Indicates whether this error will always be returned for this
            request, or retrying could change the outcome
          example: false
          type: boolean
        Details:
          description: Description of the issue
          example: Latitude is missing, invalid, or could not be determined from address
            fields.
          maxLength: 150
          minLength: 0
          nullable: true
          type: string
      required:
      - Description
      - ReasonCode
      - Recoverable
      - Source
      type: object
    ErrorResponse:
      description: Only returned in the event of an error condition
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
      required:
      - Errors
      type: object
    Errors:
      description: Only returned in the event of an error condition
      example:
        Errors:
        - Error:
            Source: latitude
            ReasonCode: INVALID_INPUT_VALUE
            Description: Latitude is missing, invalid, or could not be determined
              from address fields.
            Recoverable: false
            Details: null
      properties:
        Error:
          description: An error object
          example:
          - Error:
              Source: latitude
              ReasonCode: INVALID_INPUT_VALUE
              Description: Latitude is missing, invalid, or could not be determined
                from address fields.
              Recoverable: false
              Details: null
          items:
            $ref: '#/components/schemas/Error'
          type: array
      required:
      - Error
      type: object
    Countries:
      description: List of countries
      example:
        countries:
        - countryName: United States
          countryCode: USA
      properties:
        countries:
          description: countries
          example:
          - countryName: United States
            countryCode: USA
          items:
            $ref: '#/components/schemas/Country'
          type: array
      type: object
    CountrySubdivisions:
      description: List of country subdivisions
      example:
        countrySubdivisions:
        - countrySubdivisionName: Alabama
          countrySubdivisionCode: AL
      properties:
        countrySubdivisions:
          description: countrySubdivisions
          example:
          - countrySubdivisionName: Alabama
            countrySubdivisionCode: AL
          items:
            $ref: '#/components/schemas/CountrySubdivision'
          type: array
      type: object
    Categories:
      description: List of merchant categories
      example:
        categories:
        - categoryName: Apparel
          categoryId: 1
      properties:
        categories:
          description: categories
          example:
          - categoryName: Apparel
            categoryId: 1
          items:
            $ref: '#/components/schemas/Category'
          type: array
      type: object

